[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bear_demo"
version = "0.0.1"
authors = [
  { name="Chen Bear", email="chenll7@outlook.com" },
]
description = "Bear python demo."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
bear_demo = "bear_demo.main:main"