[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "bear_demo/_version.py"

[project]
name = "bear_demo"
dynamic = ['version']
authors = [
  { name="Chen Bear", email="chenll7@outlook.com" },
]
description = "Bear python demo."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
bear_demo = "bear_demo.main:main"